apiVersion: v1
kind: Secret
metadata:
  name: healthcare-secrets
  namespace: healthcare-platform
type: Opaque
stringData:
  JWT_SECRET: "secretkey12345"
  PATIENT_MONGO_URI: "mongodb+srv://Savidu:12345@cluster0.lbdfx9b.mongodb.net/patient_db?appName=Cluster0"
  DOCTOR_MONGO_URI: "mongodb+srv://Savidu:12345@cluster0.lbdfx9b.mongodb.net/doctor_db?appName=Cluster0"
  APPOINTMENT_MONGO_URI: "mongodb+srv://Savidu:12345@cluster0.lbdfx9b.mongodb.net/appointment_db?appName=Cluster0"
  TELEMEDICINE_MONGO_URI: "mongodb+srv://Savidu:12345@cluster0.lbdfx9b.mongodb.net/patient_db?appName=Cluster0"
  AI_MONGO_URI: "mongodb+srv://Savidu:12345@cluster0.lbdfx9b.mongodb.net/patient_db?appName=Cluster0"
  PAYMENT_MONGO_URI: "mongodb+srv://Savidu:12345@cluster0.lbdfx9b.mongodb.net/Payment_db?appName=Cluster0"
  GROQ_API_KEY: "gsk_placeholder_key_remove_secret"
  STRIPE_SECRET_KEY: "sk_test_placeholder_key_remove_secret"
  EMAIL_USER: "healthcare.info48@gmail.com"
  EMAIL_PASS: "zgveefezuyxqmspf"
  TEXTLK_API_TOKEN: "4565|Pp9C3b1tDavFUTHyMZqc9ZcDP8AHMHYgYnJGFfmReaff9d8a"
  TEXTLK_SENDER_ID: "TextLKDemo"
