apiVersion: v1
kind: Secret
metadata:
  name: healthcare-secrets
  namespace: healthcare-platform
type: Opaque
stringData:
  JWT_SECRET: "replace-me"
  PATIENT_MONGO_URI: "replace-me"
  DOCTOR_MONGO_URI: "replace-me"
  APPOINTMENT_MONGO_URI: "replace-me"
  TELEMEDICINE_MONGO_URI: "replace-me"
  AI_MONGO_URI: "replace-me"
  PAYMENT_MONGO_URI: "replace-me"
  GROQ_API_KEY: "replace-me"
  STRIPE_SECRET_KEY: "replace-me"
  EMAIL_USER: "replace-me"
  EMAIL_PASS: "replace-me"
  TEXTLK_API_TOKEN: "replace-me"
  TEXTLK_SENDER_ID: "replace-me"
